# /// script
# requires-python = ">=3.10"
# dependencies = ["httpx>=0.27"]
# ///
"""
One-stop build for the in-browser CAMotics core (wasm) + parcel app.

    uv run wasm/build_wasm.py                # fetch deps if missing, compile, link
    uv run wasm/build_wasm.py --clean        # wipe build objects + outputs, rebuild
    uv run wasm/build_wasm.py --clean-all    # also re-fetch pinned deps (~1.5G)
    uv run wasm/build_wasm.py --fetch-only   # provision deps/toolchain only, no build
    uv run wasm/build_wasm.py --build-app    # release (-O3+LTO) wasm + parcel app -> dist, no serve
    uv run wasm/build_wasm.py --serve        # build the app too + serve dist on :8000
    uv run wasm/build_wasm.py --serve --port 8101

Provisions (pinned by SHA, idempotent): cbang, libexpat, and the emsdk toolchain.
Writes cbang/include/cbang/config.h directly (the only generated header the wasm
compile needs) — no native scons build, no system -dev packages. Then compiles the
CAMotics core + cbang subset + boost(fs/iostreams) + expat + the embind glue +
a std::regex shim for cb::Regex (wasm/regex_std.cpp, replacing cbang's re2-backed
Regex.cpp) with emscripten, archives to libcamcore.a, and links to
wasm/app/src/wasm/camotics.{js,wasm}. Everything builds on the emscripten toolchain
alone; nothing native is compiled.
"""
import argparse, io, os, shutil, stat, subprocess, sys, tarfile
from pathlib import Path

import httpx

WASM = Path(__file__).resolve().parent
ROOT = WASM.parent

# ---------------------------------------------------------------------------
# Provisioning (pinned third-party deps + emsdk toolchain + native cbang headers)
# ---------------------------------------------------------------------------
DEPS = [
    dict(name="cbang",    owner="CauldronDevelopmentLLC", repo="cbang",
         sha="cbb4043a1e5214a26bf444c398d53e3b22a6d39f"),
    dict(name="libexpat", owner="libexpat",               repo="libexpat",
         sha="059910e278223e36f45337cf6e44cf25750d7803"),
    dict(name="emsdk",    owner="emscripten-core",        repo="emsdk",
         sha="d223ae73c6998296e3ab27cf81dc2c2c9fd383de"),
]
EMSDK_VERSION = "6.0.0"


def log(msg):
    print(f"[build] {msg}", flush=True)


def download_extract(dep):
    target = WASM / dep["name"]
    if target.exists():
        log(f"{dep['name']}: present, skipping download")
        return target
    url = f"https://github.com/{dep['owner']}/{dep['repo']}/archive/{dep['sha']}.tar.gz"
    log(f"{dep['name']}: downloading @ {dep['sha'][:10]}")
    buf = io.BytesIO()
    with httpx.stream("GET", url, follow_redirects=True, timeout=180) as r:
        r.raise_for_status()
        for chunk in r.iter_bytes(1 << 20):
            buf.write(chunk)
    buf.seek(0)
    log(f"{dep['name']}: extracting")
    with tarfile.open(fileobj=buf, mode="r:gz") as t:
        t.extractall(WASM, filter="data")
    (WASM / f"{dep['repo']}-{dep['sha']}").rename(target)
    return target


def setup_emsdk(emsdk):
    if (emsdk / "upstream" / "emscripten" / "emcc").exists():
        log(f"emsdk: toolchain {EMSDK_VERSION} already active")
        return
    emsdk_bin = emsdk / "emsdk"
    emsdk_bin.chmod(emsdk_bin.stat().st_mode | stat.S_IEXEC)
    log(f"emsdk: install {EMSDK_VERSION} (downloads ~1.5G toolchain)")
    subprocess.run([str(emsdk_bin), "install", EMSDK_VERSION], cwd=emsdk, check=True)
    subprocess.run([str(emsdk_bin), "activate", EMSDK_VERSION], cwd=emsdk, check=True)


# cbang's native scons build does two things the wasm compile depends on: it emits
# include/cbang/config.h, and it copies a few bundled third-party headers into include/.
# We reproduce both directly (no scons, no apt -dev packages):
#
#   config.h  — the only generated header the compile needs. The defines mirror what the
#               native build produced on the hosts we tested; hardcoding makes the build
#               host-independent (a stray -dev package can no longer perturb it).
#   headers   — only bzlib.h + lz4*.h are transitively reachable from the compiled subset
#               (cbang/comp/CompressionFilter.h <- os/SystemUtilities.cpp). re2/yaml are
#               intentionally NOT staged: Regex.cpp is replaced by regex_std.cpp and the
#               YAML readers are excluded from compilation.
CBANG_CONFIG_H = """\
// Autogenerated by wasm/build_wasm.py (replaces cbang's native scons config.h)
#pragma once

#define HAVE_EPOLL
#define HAVE_LOCAL_BOOST
#define HAVE_OPENSSL
#define HAVE_PTHREADS
"""

CBANG_VENDOR_HEADERS = [   # (source in cbang tree, destination basename under include/)
    ("src/bzip2/bzlib.h",            "bzlib.h"),
    ("src/lz4/lz4.h",                "lz4.h"),
    ("src/lz4/lz4frame.h",           "lz4frame.h"),
    ("src/lz4/lz4frame_static.h",    "lz4frame_static.h"),
    ("src/lz4/lz4hc.h",              "lz4hc.h"),
]


def stage_cbang_headers(cbang):
    inc = cbang / "include"
    (inc / "cbang").mkdir(parents=True, exist_ok=True)
    (inc / "cbang" / "config.h").write_text(CBANG_CONFIG_H)
    for src, dst in CBANG_VENDOR_HEADERS:
        shutil.copyfile(cbang / src, inc / dst)
    log(f"cbang: wrote config.h + staged {len(CBANG_VENDOR_HEADERS)} vendor headers "
        "(no native build needed)")


# expat's lib/*.c #include "expat_config.h", which is NOT in the source tarball — it's
# normally produced by expat's autotools/cmake configure. We don't run either, so write
# a static one tuned for the emscripten target (little-endian wasm; the XML_* knobs match
# the -D flags the emcc compile already passes). Without this a fresh checkout fails to
# compile xmlparse/xmlrole/xmltok (it only "worked" locally on a stale generated copy).
EXPAT_CONFIG_H = """\
#ifndef EXPAT_CONFIG_H
#define EXPAT_CONFIG_H
#define BYTEORDER 1234
#define HAVE_MEMMOVE 1
#define HAVE_STDINT_H 1
#define HAVE_STRING_H 1
#define HAVE_STDLIB_H 1
#define XML_GE 1
#define XML_NS 1
#define XML_DTD 1
#define XML_CONTEXT_BYTES 1024
#define XML_POOR_ENTROPY 1
#endif
"""


def write_expat_config(libexpat):
    cfg = libexpat / "expat" / "lib" / "expat_config.h"
    cfg.write_text(EXPAT_CONFIG_H)
    log(f"expat: wrote {cfg.relative_to(WASM)} (replaces autotools/cmake configure)")


def verify_deps():
    checks = {
        "emcc":          WASM / "emsdk" / "upstream" / "emscripten" / "emcc",
        "expat source":  WASM / "libexpat" / "expat" / "lib" / "xmlparse.c",
        "expat config":  WASM / "libexpat" / "expat" / "lib" / "expat_config.h",
        "cbang config":  WASM / "cbang" / "include" / "cbang" / "config.h",
        "cbang bzlib":   WASM / "cbang" / "include" / "bzlib.h",
    }
    ok = True
    for label, path in checks.items():
        present = path.exists()
        ok = ok and present
        log(("ok    " if present else "MISSING ") + f"{label}: {path.relative_to(WASM)}")
    return ok


def provision(deep_clean=False):
    for dep in DEPS:
        download_extract(dep)
    setup_emsdk(WASM / "emsdk")
    stage_cbang_headers(WASM / "cbang")
    write_expat_config(WASM / "libexpat")
    if not verify_deps():
        sys.exit("setup incomplete — see MISSING above")


# ---------------------------------------------------------------------------
# Compile + link (emscripten). Mirrors the old build_wasm.sh exactly.
# ---------------------------------------------------------------------------
# RELEASE is flipped on by --build-app; it selects -O3+LTO (vs -O2), drops
# -sASSERTIONS, and uses a separate object dir so debug/release .o files (the
# staleness check is mtime-only, not flag-aware) never get cross-reused.
RELEASE = False
OBJ = WASM / "wobj"
EXPAT = WASM / "libexpat" / "expat" / "lib"
INC = ["-Iwasm/cbang/src", "-Iwasm/cbang/include", "-Iwasm/cbang/src/boost",
       f"-I{EXPAT}", "-Isrc", "-Ibuild"]
# Optimization flags (-O2/-O3 +LTO) are prepended per-call in build_wasm().
DEF = ["-std=c++17", "-fexceptions",
       "-DHAVE_CBANG", "-DUSING_CBANG", "-DCAMOTICS_NO_TPL"]
PTHREAD = os.environ.get("PTHREAD", "").split()  # empty (v1 is single-threaded)
LOG = WASM / "build_wasm.log"

# core CAMotics source globs (relative to ROOT), and the one excluded TPL file.
CORE_GLOBS = [
    "src/gcode/*.cpp", "src/gcode/ast/*.cpp", "src/gcode/parse/*.cpp",
    "src/gcode/interp/*.cpp", "src/gcode/machine/*.cpp", "src/gcode/plan/*.cpp",
    "src/gcode/plan/bbctrl/*.cpp", "src/stl/*.cpp", "src/dxf/*.cpp", "src/dxflib/*.cpp",
    "src/camotics/*.cpp", "src/camotics/sim/*.cpp", "src/camotics/probe/*.cpp",
    "src/camotics/opt/*.cpp", "src/camotics/project/*.cpp",
    "src/camotics/contour/*.cpp", "src/camotics/render/*.cpp",
]
# cbang subset (relative to wasm/cbang); skip Random.cpp (needs openssl).
CBANG_GLOBS = [
    "src/cbang/*.cpp", "src/cbang/geom/*.cpp", "src/cbang/json/*.cpp",
    "src/cbang/json/schema/*.cpp", "src/cbang/xml/*.cpp", "src/cbang/util/*.cpp",
    "src/cbang/os/*.cpp", "src/cbang/os/lin/*.cpp", "src/cbang/thread/*.cpp",
    "src/cbang/time/*.cpp", "src/cbang/log/*.cpp", "src/cbang/parse/*.cpp",
    "src/cbang/io/*.cpp", "src/cbang/config/*.cpp",
    "src/cbang/debug/*.cpp", "src/cbang/enum/*.cpp", "src/cbang/js/*.cpp",
    "src/cbang/net/Base64.cpp", "src/cbang/net/URI.cpp",
]

_failed = []


def _globs(base, patterns):
    out = []
    for pat in patterns:
        out += sorted(base.glob(pat))
    return out


def compile_one(prefix, src, cwd, flags, compiler="em++", log_fh=None):
    """Compile src->obj if the obj is stale. Returns the obj path (always, so it
    gets archived even when skipped). Records failures in _failed."""
    rel = src.relative_to(cwd)
    obj = OBJ / f"{prefix}__{str(rel).replace('/', '_')}.o"
    if obj.exists() and obj.stat().st_mtime >= src.stat().st_mtime:
        return obj
    rc = subprocess.run([compiler, *flags, "-c", str(rel), "-o", str(obj)],
                        cwd=cwd, stderr=log_fh).returncode
    if rc != 0:
        _failed.append(str(rel))
        print(f"FAILCOMPILE {rel}", flush=True)
    return obj


def emsdk_env():
    """Source emsdk_env.sh and capture the resulting environment (PATH etc.)."""
    script = WASM / "emsdk" / "emsdk_env.sh"
    out = subprocess.run(
        ["bash", "-c", f"source '{script}' >/dev/null 2>&1 && env -0"],
        capture_output=True, text=True, check=True).stdout
    env = {}
    for entry in out.split("\0"):
        if "=" in entry:
            k, v = entry.split("=", 1)
            env[k] = v
    return env or dict(os.environ)


def build_wasm():
    global OBJ
    OBJ = WASM / ("wobj-release" if RELEASE else "wobj")
    optflags = ["-O3", "-flto"] if RELEASE else ["-O2"]  # -flto on compile AND link
    assertions = "-sASSERTIONS=0" if RELEASE else "-sASSERTIONS=1"
    log(f"build mode: {'RELEASE (-O3 +LTO, no assertions)' if RELEASE else 'debug (-O2)'}")
    OBJ.mkdir(parents=True, exist_ok=True)
    os.environ.update(emsdk_env())  # put em++/emcc/emar on PATH for all subprocesses
    LOG.write_text("")
    _failed.clear()
    cbang = WASM / "cbang"

    with open(LOG, "a") as fh:
        print("=== CAMotics core ===", flush=True)
        core_objs = []
        for f in _globs(ROOT, CORE_GLOBS):
            if f.name == "TPLRunner.cpp":   # TPL-only, excluded
                continue
            core_objs.append(compile_one("core", f, ROOT, optflags + DEF + PTHREAD + INC, log_fh=fh))
        print(f"  core: {len(core_objs)} files", flush=True)

        print("=== cbang subset ===", flush=True)
        cbinc = ["-Isrc", "-Iinclude", "-Isrc/boost", f"-I{EXPAT}"]
        # Skip the lone consumers of native re2/yaml headers. Random.cpp needs openssl.
        # Regex.cpp (<re2/re2.h>) is replaced by wasm/regex_std.cpp (std::regex) below.
        # YAML{Reader,MergeSink}.cpp (<yaml.h>) are dead in the wasm core (no YAML
        # parsing); their symbols link as allowed-undefined and are never called.
        cbang_skip = {"Random.cpp", "Regex.cpp", "YAMLReader.cpp", "YAMLMergeSink.cpp"}
        cbang_objs = []
        for f in _globs(cbang, CBANG_GLOBS):
            if f.name in cbang_skip:
                continue
            cbang_objs.append(compile_one("cbang", f, cbang, optflags + DEF + PTHREAD + cbinc, log_fh=fh))

        # NB: cbang's bundled re2 is no longer compiled — cb::Regex is provided by
        # wasm/regex_std.cpp (std::regex), so nothing references re2 symbols.

        print("=== boost subset (filesystem + iostreams core; NO atomic/compression) ===", flush=True)
        boost_objs = []
        for f in _globs(cbang, ["src/boost/libs/filesystem/src/*.cpp",
                                "src/boost/libs/iostreams/src/*.cpp"]):
            if f.name in ("bzip2.cpp", "lzma.cpp", "zstd.cpp"):
                continue
            boost_objs.append(compile_one(
                "boost", f, cbang,
                optflags + DEF + PTHREAD + ["-Isrc", "-Isrc/boost", "-fexceptions", "-sUSE_ZLIB=1"],
                log_fh=fh))

        print("=== expat (xmlparse/xmlrole/xmltok) ===", flush=True)
        expat_objs = []
        for name in ("xmlparse.c", "xmlrole.c", "xmltok.c"):
            src = EXPAT / name
            obj = OBJ / f"expat__{name}.o"
            if not (obj.exists() and obj.stat().st_mtime >= src.stat().st_mtime):
                rc = subprocess.run(
                    ["emcc", *optflags, *PTHREAD, "-DXML_GE=1", "-DXML_POOR_ENTROPY",
                     "-DXML_STATIC", f"-I{EXPAT}", "-c", str(src), "-o", str(obj)],
                    stderr=fh).returncode
                if rc != 0:
                    _failed.append(name)
                    print(f"FAILCOMPILE {name}", flush=True)
            expat_objs.append(obj)

        print("=== embind glue + comp stub + regex shim ===", flush=True)
        glue_o = compile_one("glue", WASM / "glue.cpp", ROOT, optflags + DEF + PTHREAD + INC, log_fh=fh)
        comp_o = compile_one("glue", WASM / "comp_stub.cpp", ROOT, optflags + DEF + PTHREAD + INC, log_fh=fh)
        # std::regex implementation of cb::Regex, replacing cbang's re2-backed Regex.cpp.
        regex_o = compile_one("glue", WASM / "regex_std.cpp", ROOT, optflags + DEF + PTHREAD + INC, log_fh=fh)

        print("=== archive ===", flush=True)
        ar = OBJ / "libcamcore.a"
        ar.unlink(missing_ok=True)
        lib_objs = core_objs + cbang_objs + boost_objs + expat_objs
        subprocess.run(["emar", "rcs", str(ar), *map(str, lib_objs)], stderr=fh, check=False)
        print(f"  archive: {ar.stat().st_size if ar.exists() else 0} bytes, {len(lib_objs)} objs",
              flush=True)

        print("=== link ===", flush=True)
        out_js = WASM / "app" / "src" / "wasm" / "camotics.js"
        out_js.parent.mkdir(parents=True, exist_ok=True)
        link = subprocess.run(
            ["em++", *optflags, "-fexceptions", *PTHREAD, "--bind",
             "-sMODULARIZE=1", "-sEXPORT_NAME=createCAMotics", "-sEXPORT_ES6=1",
             "-sALLOW_MEMORY_GROWTH=1", "-sENVIRONMENT=web", assertions,
             "-sEXPORTED_RUNTIME_METHODS=FS",
             "-sERROR_ON_UNDEFINED_SYMBOLS=0", "-sUSE_ZLIB=1",
             str(glue_o), str(comp_o), str(regex_o), str(ar), "-o", str(out_js)],
            stderr=fh).returncode

    fails = len(_failed)
    print(f"link exit={link}", flush=True)
    print(f"=== FAILCOMPILE count: {fails} ===", flush=True)
    if link != 0:
        text = LOG.read_text(errors="replace")
        undef = sorted({l.split("undefined symbol: ", 1)[1].split()[0]
                        for l in text.splitlines() if "undefined symbol: " in l})
        if undef:
            print("=== undefined symbols (unique) ===", flush=True)
            print("\n".join(undef[:50]), flush=True)
        sys.exit("wasm link failed (see wasm/build_wasm.log)")
    if fails:
        sys.exit(f"{fails} translation unit(s) failed to compile (see wasm/build_wasm.log)")
    wasm_out = WASM / "app" / "src" / "wasm" / "camotics.wasm"
    log(f"built {wasm_out.relative_to(WASM)} ({wasm_out.stat().st_size // 1024} KB)")


# ---------------------------------------------------------------------------
# clean + serve
# ---------------------------------------------------------------------------
def clean(deep=False):
    # Wipe everything the build produces: object dirs, the linked wasm core, and
    # the built static site. Leaves provisioned deps (emsdk/cbang/libexpat) unless
    # deep. node_modules is left alone — `npm ci` rewrites it deterministically.
    targets = [WASM / "wobj", WASM / "wobj-release",
               WASM / "app" / "src" / "wasm" / "camotics.js",
               WASM / "app" / "src" / "wasm" / "camotics.wasm",
               WASM / "app" / "dist"]
    if deep:
        targets += [WASM / "cbang", WASM / "emsdk", WASM / "libexpat"]
    for t in targets:
        if t.is_dir():
            shutil.rmtree(t); log(f"removed {t.relative_to(WASM)}/")
        elif t.exists():
            t.unlink(); log(f"removed {t.relative_to(WASM)}")


def build_app():
    # Build the static site into wasm/app/dist. `parcel build` is a minified
    # production bundle. check=True so CI fails loudly on any npm error.
    app = WASM / "app"
    log("npm ci")
    subprocess.run(["npm", "ci"], cwd=app, check=True)
    log("building parcel app (npm run build)")
    subprocess.run(["npm", "run", "build"], cwd=app, check=True)
    log(f"built {(app / 'dist').relative_to(WASM)}/")


def serve(port):
    app = WASM / "app"
    build_app()
    log(f"serving wasm/app/dist on 0.0.0.0:{port} (Ctrl-C to stop)")
    subprocess.run([sys.executable, str(app / "serve_dist.py"), str(port)], cwd=app)


def main():
    ap = argparse.ArgumentParser(description="Provision, build, and serve the CAMotics wasm app.")
    ap.add_argument("--clean", action="store_true",
                    help="remove build objects + outputs before building")
    ap.add_argument("--clean-all", action="store_true",
                    help="--clean plus re-fetch deps (re-downloads ~1.5G)")
    ap.add_argument("--fetch-only", action="store_true",
                    help="provision deps/toolchain only; skip the wasm build")
    ap.add_argument("--build-app", action="store_true",
                    help="release build (-O3+LTO) of the wasm core AND the parcel app "
                         "into wasm/app/dist; no serving (for CI / deploy)")
    ap.add_argument("--serve", action="store_true", help="build the app + serve dist after building")
    ap.add_argument("--port", type=int, default=8000, help="serve port (default 8000)")
    args = ap.parse_args()

    if args.clean or args.clean_all:
        clean(deep=args.clean_all)

    provision()

    if args.fetch_only:
        log("deps ready (--fetch-only). Build with:  uv run wasm/build_wasm.py")
        return

    if args.build_app:
        global RELEASE
        RELEASE = True
        build_wasm()
        build_app()
        log("done. Static site is in wasm/app/dist/")
        return

    build_wasm()
    if args.serve:
        serve(args.port)
    else:
        log("done. Serve with:  uv run wasm/build_wasm.py --serve")


if __name__ == "__main__":
    main()
